//user
export const CREATE_USER_FACTORY = 'CREATE_USER_FACTORY';
export const UPDATE_USER_FACTORY = 'UPDATE_USER_FACTORY';
export const DELETE_USER_FACTORY = 'DELETE_USER_FACTORY';

//transaction
export const CREATE_TRANSACTION_FACTORY = 'CREATE_TRANSACTION_FACTORY';
