//user
export const CREATE_USER_FACTORY = 'CREATE_USER_FACTORY';
export const UPDATE_USER_FACTORY = 'UPDATE_USER_FACTORY';
export const DELETE_USER_FACTORY = 'DELETE_USER_FACTORY';

//transaction
export const CREATE_TRANSACTION_FACTORY = 'CREATE_TRANSACTION_FACTORY';
export const FIND_TRANSACTION_BY_ID_FACTORY = 'FIND_TRANSACTION_BY_ID_FACTORY';
export const FIND_TRANSACTION_BY_CLIENT_ID_FACTORY =
  'FIND_TRANSACTION_BY_CLIENT_ID_FACTORY';
